# Generated by Django 5.0.3 on 2024-04-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
